Tuldes y typos arreglados en el post
anderkws/hyperblog pull request #1
Opened 2024-04-03 03:32 UTC by anderkws

No debemos mandar esto todavía a la rama master

2024-04-04 03:46 UTC, AnitaContorcionista requested changes
En de usar tildes directas usar entidades HTML

2024-04-04 04:04 UTC, anderkws commented
Cambios hechos, por favor hazme el merge

2024-04-11 04:00 UTC, AnitaContorcionista commented
> Cambios hechos, por favor hazme el merge

2024-04-11 04:00 UTC, closed without merging

2024-04-11 04:02 UTC, AnitaContorcionista reviewed
Excelente eso era 1